/* ===========================================================================
   TCAS70 — lexicon.js
   The predicted B2+ word bank for A-Level English (82), March 2570 / 2027.
   Built from the rare-word profile of TCAS61–69 (every word below either
   appeared in a past paper, belongs to the same family, or belongs to a theme
   the papers return to), plus the news radar for Sept 2025 – Sept 2026.

   Each entry: [word, part of speech, CEFR estimate, theme, English meaning,
                Thai meaning, example sentence]
   Themes:
     ai   AI & digital life            soc  social media & media literacy
     clim climate & energy             dis  disasters & early warning
     eco  waste, pollution, consumption health health & wellbeing
     work education, skills & jobs     cult culture, communication, society
     cons consumer texts (ads, reviews) acad general academic words
     tone tone & attitude words        trend graphs & numbers
     org  text organisation words      id   idioms & sayings
     dm   discourse markers (speech)
   =========================================================================== */

var LEXICON = [
  /* ---------------------------------------------------------------- AI */
  ['generative AI','n','B2','ai','AI that creates new text, images, audio or video from a prompt','ปัญญาประดิษฐ์เชิงสร้างสรรค์ที่สร้างเนื้อหาใหม่ได้','Generative AI can turn a one-line prompt into a realistic video.'],
  ['deepfake','n','B2+','ai','a fake video or recording made with AI to look real','คลิปหรือเสียงปลอมที่สร้างด้วย AI ให้ดูเหมือนจริง','The deepfake showed a minister saying words he never said.'],
  ['algorithm','n','B2','ai','a set of rules a computer follows to make decisions','ชุดคำสั่งหรือขั้นตอนที่คอมพิวเตอร์ใช้ตัดสินใจ','The algorithm decides which clips appear on your feed.'],
  ['chatbot','n','B2','ai','a program that holds conversations with users','โปรแกรมสนทนาอัตโนมัติ','The bank replaced its call centre with a chatbot.'],
  ['automate','v','B2','ai','to make a process work by machine, without people','ทำให้เป็นระบบอัตโนมัติ','Many firms plan to automate routine paperwork.'],
  ['authenticity','n','C1','ai','the quality of being real or genuine','ความจริงแท้ ความน่าเชื่อถือว่าเป็นของจริง','Experts check the authenticity of every viral clip.'],
  ['verify','v','B2','ai','to check that something is true','ตรวจสอบยืนยันความถูกต้อง','Always verify a story before you share it.'],
  ['disinformation','n','C1','ai','false information spread on purpose','ข้อมูลเท็จที่จงใจเผยแพร่','The app was used to spread disinformation before the election.'],
  ['misinformation','n','B2+','ai','false information spread by mistake','ข้อมูลผิดที่ถูกแชร์ต่อโดยไม่ตั้งใจ','Health misinformation spreads faster than corrections.'],
  ['privacy','n','B2','ai','the right to keep personal information to yourself','ความเป็นส่วนตัว','Face-scanning cameras raise serious privacy concerns.'],
  ['data breach','n','B2+','ai','an incident in which private data is stolen or exposed','การรั่วไหลของข้อมูล','The data breach exposed two million passwords.'],
  ['consent','n','B2+','ai','permission for something to happen','ความยินยอม','Your data should not be shared without your consent.'],
  ['bias','n','B2+','ai','an unfair preference for or against a group','อคติ ความลำเอียง','If training data contains bias, the system will repeat it.'],
  ['hallucination','n','C1','ai','(AI) a confident answer that is false or invented','การที่ AI สร้างคำตอบที่ผิดหรือแต่งขึ้นอย่างมั่นใจ','The chatbot\'s hallucination included a book that does not exist.'],
  ['surveillance','n','C1','ai','close watching of people, often by cameras or data','การเฝ้าติดตาม การสอดแนม','Critics fear AI surveillance in shops.'],
  ['cybersecurity','n','B2+','ai','protection of computer systems from attack','ความมั่นคงปลอดภัยทางไซเบอร์','Schools now teach basic cybersecurity.'],
  ['scam','n/v','B2','ai','a dishonest trick to get money','การหลอกลวงต้มตุ๋น','A scam call pretended to be from the post office.'],
  ['copycat','n','C1','ai','a person or company that copies another','ผู้เลียนแบบ','Copycat apps appeared within weeks.'],
  ['early adopter','n','C1','ai','one of the first people to use a new product','ผู้ที่รับเทคโนโลยีใหม่ไปใช้เป็นกลุ่มแรก','Early adopters posted the first AI videos.'],
  ['digital literacy','n','B2+','ai','the ability to use and judge digital information well','ความฉลาดรู้ทางดิจิทัล','Digital literacy is now as important as reading.'],

  /* ---------------------------------------------------------------- SOCIAL MEDIA / MEDIA LITERACY */
  ['engagement','n','B2+','soc','how much users like, share and comment','การมีส่วนร่วม (ไลก์ แชร์ คอมเมนต์)','TikTok engagement rose sharply after 2020.'],
  ['influencer','n','B2','soc','a person paid or followed for their online opinions','ผู้มีอิทธิพลบนโลกออนไลน์','The influencer did not say the post was an advert.'],
  ['go viral','v phr','B2','soc','to spread very quickly online','แพร่กระจายอย่างรวดเร็วบนโลกออนไลน์','The meme went viral overnight.'],
  ['echo chamber','n','C1','soc','a space where people hear only views like their own','ห้องเสียงสะท้อน (ได้ยินแต่ความเห็นแบบเดียวกัน)','Algorithms can trap users in an echo chamber.'],
  ['doomscrolling','n','C1','soc','reading bad news online for too long','การไถอ่านข่าวร้ายไม่หยุด','Doomscrolling before bed ruins sleep.'],
  ['screen time','n','B2','soc','time spent looking at a phone, computer or TV','เวลาที่ใช้หน้าจอ','Parents set limits on screen time.'],
  ['age verification','n','C1','soc','checking a user\'s age before giving access','การยืนยันอายุผู้ใช้','Weak age verification let under-16s keep their accounts.'],
  ['ban','n/v','B2','soc','an official rule that stops something','การห้าม คำสั่งห้าม','Australia\'s ban on under-16 accounts began in December 2025.'],
  ['compliance','n','C1','soc','obeying a rule or law','การปฏิบัติตาม (กฎ)','Platforms that cannot show compliance with the age rules may face large fines.'],
  ['satire','n','C1','soc','humour that mocks people or ideas to criticise them','การเสียดสี','The meme was a satire of strict entry rules.'],
  ['relatable','adj','B2+','soc','easy to connect with because it feels like your life','ที่รู้สึกเข้าถึงหรือเชื่อมโยงได้','Memes make a blog feel relatable.'],
  ['anonymous','adj','B2','soc','with no name given','ไม่ระบุชื่อ','Anonymous messages make cyberbullying worse.'],
  ['cyberbullying','n','B2','soc','bullying through phones or the internet','การกลั่นแกล้งทางไซเบอร์','Cyberbullying can continue 24 hours a day.'],
  ['addictive','adj','B2','soc','hard to stop using','ที่ทำให้เสพติด','Endless scrolling is designed to be addictive.'],
  ['credible','adj','C1','soc','able to be believed; trustworthy','น่าเชื่อถือ','Check whether the source is credible.'],

  /* ---------------------------------------------------------------- CLIMATE & ENERGY */
  ['greenhouse gas','n','B2','clim','a gas such as CO2 that traps heat','ก๊าซเรือนกระจก','Dairy milk emits more greenhouse gas than oat milk.'],
  ['emission','n','B2+','clim','gas or heat sent into the air','การปล่อย (ก๊าซ)','Carbon emissions reached a record high.'],
  ['carbon footprint','n','B2+','clim','the total greenhouse gas caused by a person or product','ปริมาณคาร์บอนที่เกิดจากกิจกรรมหรือสินค้า','Flying doubles your carbon footprint.'],
  ['net zero','n','C1','clim','balance where no extra greenhouse gas is added','การปล่อยก๊าซสุทธิเป็นศูนย์','Thailand aims to reach net zero by 2065.'],
  ['renewable','adj','B2','clim','(energy) that does not run out, e.g. sun, wind','(พลังงาน) หมุนเวียน','The cost of renewables is falling fast.'],
  ['fossil fuel','n','B2','clim','coal, oil or gas','เชื้อเพลิงฟอสซิล','EVs reduce reliance on fossil fuels.'],
  ['heatwave','n','B2','clim','a period of unusually hot weather','คลื่นความร้อน','The heatwave closed schools for a week.'],
  ['El Niño','n','C1','clim','warming of the Pacific that brings drought to Thailand','ปรากฏการณ์เอลนีโญ','A strong El Niño could mean drought in 2027.'],
  ['drought','n','B2','clim','a long period without rain','ภัยแล้ง','Five years of drought forced farmers to move.'],
  ['mitigate','v','C1','clim','to make something bad less serious','บรรเทา ลดความรุนแรง','Trees help mitigate urban heat.'],
  ['adaptation','n','C1','clim','changing to cope with new conditions','การปรับตัว','Adaptation includes building higher flood walls.'],
  ['sustainable','adj','B2','clim','able to continue without harming the environment','ยั่งยืน','Sustainable farming protects the soil.'],
  ['decarbonise','v','C1','clim','to cut the carbon a system produces','ลดการปล่อยคาร์บอน','Airlines are slow to decarbonise.'],
  ['extinction','n','B2+','clim','the dying out of a whole species','การสูญพันธุ์','Coral faces extinction above 1.5°C of warming.'],
  ['scarcity','n','C1','clim','a shortage','ความขาดแคลน','Warming could cause food scarcity.'],

  /* ---------------------------------------------------------------- DISASTERS */
  ['flash flood','n','B2+','dis','a sudden flood after very heavy rain','น้ำท่วมฉับพลัน','The flash flood hit while campers were asleep.'],
  ['monsoon','n','B2','dis','the season of heavy rain in South and Southeast Asia','มรสุม','Monsoon rains can flood whole provinces.'],
  ['evacuate','v','B2','dis','to move people away from danger','อพยพ','Residents were told to evacuate by midnight.'],
  ['evacuation','n','B2','dis','moving people away from danger','การอพยพ','The evacuation began at 4 a.m.'],
  ['early warning','n','B2+','dis','an alert given before a disaster arrives','การเตือนภัยล่วงหน้า','A siren system gives early warning of floods.'],
  ['cell broadcast','n','C1','dis','an alert sent to every phone in an area','การแจ้งเตือนผ่านระบบ cell broadcast','Bangkok used cell broadcast to warn residents.'],
  ['submerged','adj','C1','dis','under water','จมอยู่ใต้น้ำ','Submerged roads blocked traffic at 37 locations.'],
  ['displaced','adj','C1','dis','forced to leave home','ต้องพลัดถิ่น ไร้ที่อยู่ชั่วคราว','Families displaced by floods may stay in shelters for weeks.'],
  ['aftermath','n','C1','dis','the period after a disaster','ผลที่ตามมาหลังเหตุการณ์','In the aftermath, questions were asked about the warnings.'],
  ['casualty','n','B2+','dis','a person killed or injured','ผู้บาดเจ็บหรือเสียชีวิต','The number of casualties rose as the water spread.'],
  ['devastate','v','B2+','dis','to destroy or badly damage','ทำลายล้าง ทำให้เสียหายอย่างหนัก','The hurricane devastated the coast.'],
  ['relief','n','B2','dis','help such as food and shelter after a disaster','ความช่วยเหลือบรรเทาทุกข์','Relief supplies reached Hat Yai by boat.'],
  ['landslide','n','B2','dis','a mass of earth sliding down a slope','ดินถล่ม','Heavy rain triggered landslides in the north.'],
  ['earthquake','n','B1','dis','a sudden shaking of the ground','แผ่นดินไหว','The 2025 earthquake shook buildings in Bangkok.'],
  ['aftershock','n','C1','dis','a smaller quake after a big one','แผ่นดินไหวตาม (อาฟเตอร์ช็อก)','Aftershocks continued for days.'],
  ['infrastructure','n','C1','dis','basic systems such as roads, drains and power','โครงสร้างพื้นฐาน','Old drainage infrastructure could not cope.'],
  ['resilient','adj','C1','dis','able to recover quickly','ฟื้นตัวได้เร็ว ยืดหยุ่น','Cities must become more resilient to floods.'],
  ['state of emergency','n','B2+','dis','an official declaration that normal rules are suspended','ภาวะฉุกเฉิน','A flood disaster zone was declared on 26 September.'],

  /* ---------------------------------------------------------------- WASTE, POLLUTION, CONSUMPTION */
  ['PM2.5','n','B2','eco','tiny dust particles that enter the lungs','ฝุ่นละอองขนาดเล็ก PM2.5','PM2.5 levels peak in the dry season.'],
  ['particulate','n/adj','C1','eco','(of) tiny particles in the air','อนุภาค (ฝุ่น)','Particulate pollution harms the brain.'],
  ['recyclable','adj','B2','eco','able to be recycled','รีไซเคิลได้','Only some plastics are recyclable.'],
  ['biodegradable','adj','B2+','eco','able to break down naturally','ย่อยสลายได้ทางชีวภาพ','Biodegradable packaging still needs the right conditions.'],
  ['landfill','n','B2+','eco','a site where rubbish is buried','หลุมฝังกลบขยะ','Most plastic ends up in landfill.'],
  ['compost','v/n','B2+','eco','to turn food waste into soil','ทำปุ๋ยหมัก','Fruit peels can be composted.'],
  ['fast fashion','n','B2+','eco','cheap clothes made quickly to follow trends','แฟชั่นแบบเร็ว (เสื้อผ้าราคาถูกผลิตเร็ว)','Fast fashion fills landfills with textiles.'],
  ['disposable','adj','B2','eco','made to be used once and thrown away','ใช้ครั้งเดียวทิ้ง','Disposable cups are hard to recycle.'],
  ['circular economy','n','C1','eco','a system that reuses materials instead of wasting them','เศรษฐกิจหมุนเวียน','A circular economy keeps materials in use.'],
  ['exploit','v','C1','eco','to treat people unfairly for profit','เอารัดเอาเปรียบ','Some factories exploit garment workers.'],
  ['toxic','adj','B2','eco','poisonous','เป็นพิษ','Batteries contain toxic chemicals.'],
  ['repurpose','v','C1','eco','to use something for a new purpose','นำกลับมาใช้ในจุดประสงค์ใหม่','Old glass is repurposed into tiles.'],
  ['greenwashing','n','C1','eco','false claims that a product is good for the environment','การฟอกเขียว (อ้างว่ารักษ์โลกเกินจริง)','The recycling logo on that cup is greenwashing.'],
  ['consumption','n','B2+','eco','the using up of goods or energy','การบริโภค','Meat consumption is falling among young people.'],

  /* ---------------------------------------------------------------- HEALTH */
  ['sedentary','adj','C1','health','involving a lot of sitting and little exercise','ที่นั่งอยู่กับที่มาก ขาดการเคลื่อนไหว','A sedentary lifestyle raises the risk of heart disease.'],
  ['immune system','n','B2','health','the body\'s defence against illness','ระบบภูมิคุ้มกัน','Vitamin D strengthens the immune system.'],
  ['intake','n','C1','health','the amount you eat or drink','ปริมาณที่รับเข้าร่างกาย','Reduce your daily sugar intake.'],
  ['symptom','n','B2','health','a sign of illness','อาการ','Fever is a common symptom.'],
  ['chronic','adj','C1','health','lasting a long time','เรื้อรัง','Chronic stress weakens the body.'],
  ['burnout','n','B2+','health','exhaustion from too much work or stress','ภาวะหมดไฟ','Excessive stress may lead to burnout.'],
  ['wellbeing','n','B2','health','being healthy and happy','ความเป็นอยู่ที่ดี สุขภาวะ','Gaming in moderation can support wellbeing.'],
  ['obesity','n','B2+','health','being very overweight','โรคอ้วน','Obesity is linked to a sedentary lifestyle.'],
  ['cardiovascular','adj','C1','health','of the heart and blood vessels','เกี่ยวกับหัวใจและหลอดเลือด','Plant protein lowers cardiovascular risk.'],
  ['plant-based','adj','B2','health','made from plants, not animals','ทำจากพืช','Plant-based diets are growing in popularity.'],
  ['ultra-processed','adj','C1','health','(food) made in factories with many additives','(อาหาร) แปรรูปสูง','Ultra-processed snacks are cheap but unhealthy.'],
  ['deprivation','n','C1','health','not having enough of something needed','การขาด (สิ่งจำเป็น)','Sleep deprivation affects memory.'],
  ['moderation','n','C1','health','avoiding too much of something','ความพอดี ความพอประมาณ','Stress can help when experienced in moderation.'],
  ['aging society','n','B2+','health','a society with a growing share of older people','สังคมผู้สูงอายุ','Thailand is becoming a super-aged society.'],
  ['mental health','n','B2','health','emotional and psychological wellbeing','สุขภาพจิต','Exam pressure harms students\' mental health.'],
  ['anxiety','n','B2','health','a feeling of worry and fear','ความวิตกกังวล','Anxiety raises blood pressure at the clinic.'],
  ['diagnosis','n','B2+','health','identifying an illness','การวินิจฉัยโรค','A false reading led to a wrong diagnosis.'],
  ['prescription','n','B2','health','a doctor\'s written order for medicine','ใบสั่งยา','The pills are available without a prescription.'],
  ['resistant','adj','C1','health','not affected by something (e.g. a drug)','ดื้อ (ยา) ต้านทาน','Overuse makes bacteria resistant to antibiotics.'],

  /* ---------------------------------------------------------------- EDUCATION & WORK */
  ['upskill','v','C1','work','to improve skills you already use','พัฒนาทักษะเดิมให้สูงขึ้น','Companies upskill staff to keep them.'],
  ['reskill','v','C1','work','to learn skills for a new job','เรียนรู้ทักษะใหม่เพื่องานใหม่','Factory workers reskill as technicians.'],
  ['employability','n','C1','work','how easy it is for you to get a job','ความสามารถในการได้รับการจ้างงาน','Tech skills boost employability.'],
  ['soft skills','n','B2','work','people skills such as teamwork and communication','ทักษะด้านอารมณ์และสังคม','Employers value soft skills as much as grades.'],
  ['critical thinking','n','B2','work','judging ideas carefully and logically','การคิดเชิงวิพากษ์','Critical thinking protects you from fake news.'],
  ['collaborate','v','B2+','work','to work together','ร่วมมือกัน','Students collaborate with schools abroad.'],
  ['ideation','n','C1+','work','the process of forming new ideas','กระบวนการคิดไอเดียใหม่','Ideation is a highly sought-after skill.'],
  ['academic integrity','n','C1','work','honesty in study and research','ความซื่อตรงทางวิชาการ','Using AI to write your essay breaks academic integrity.'],
  ['plagiarism','n','B2+','work','copying someone else\'s work as your own','การลอกเลียนผลงาน','The teacher suspected plagiarism.'],
  ['curriculum','n','B2+','work','the subjects taught in a course','หลักสูตร','The curriculum now includes coding.'],
  ['gig economy','n','C1','work','work made of short freelance jobs','เศรษฐกิจแบบงานอิสระระยะสั้น','Delivery riders are part of the gig economy.'],
  ['remote','adj','B2','work','done from a distance, e.g. from home','ทางไกล (ทำงานหรือเรียนจากที่อื่น)','Remote learning offers flexibility.'],
  ['autonomy','n','C1','work','freedom to make your own decisions','ความเป็นอิสระในการตัดสินใจ','Online learners value autonomy.'],
  ['prospective','adj','C1','work','likely to become (a student, buyer…)','ที่คาดว่าจะเป็น (นักศึกษา ผู้ซื้อ)','Prospective students visited the campus.'],
  ['credential','n','C1','work','a qualification proving ability','วุฒิ หลักฐานรับรองคุณสมบัติ','The tutor\'s credentials are listed in the ad.'],
  ['burn the midnight oil','idiom','C1','work','to study or work late at night','ทำงานหรืออ่านหนังสือดึกดื่น','She burned the midnight oil before TGAT.'],

  /* ---------------------------------------------------------------- CULTURE, COMMUNICATION, SOCIETY */
  ['nonverbal','adj','B2+','cult','without words (gestures, faces, tone)','อวัจนภาษา ไม่ใช้คำพูด','Nonverbal cues differ across cultures.'],
  ['gesture','n','B2','cult','a movement of the hands or head that shows meaning','ท่าทาง','A thumbs-up is a rude gesture in some countries.'],
  ['posture','n','B2+','cult','the way you hold your body','ท่าทางการยืนหรือนั่ง','Good posture signals confidence.'],
  ['intercultural','adj','C1','cult','between different cultures','ระหว่างวัฒนธรรม','Intercultural misunderstandings can ruin a deal.'],
  ['bilingual','adj','B2','cult','able to use two languages','ที่ใช้สองภาษาได้','Bilingual children often act as translators.'],
  ['heritage','n','B2+','cult','traditions passed down from the past','มรดกทางวัฒนธรรม','She speaks her heritage language at festivals.'],
  ['soft power','n','C1','cult','influence through culture and attraction, not force','อำนาจละมุน','Thai food and T-pop are sources of soft power.'],
  ['stereotype','n','B2+','cult','a fixed, oversimplified idea about a group','ภาพเหมารวม','Avoid stereotypes about introverts.'],
  ['consensus','n','C1','cult','general agreement','ฉันทามติ ความเห็นพ้อง','Japanese managers value consensus.'],
  ['introvert','n','B2+','cult','a person who gets energy from quiet time alone','คนเก็บตัว','Introverts may prefer small gatherings.'],
  ['generation','n','B2','cult','people born in the same period','รุ่น (ของคน)','Gen Z prefers face-to-face contact at work.'],
  ['overtourism','n','C1','cult','too many tourists in one place','การท่องเที่ยวที่มากเกินขีดรองรับ','Overtourism diminishes residents\' quality of life.'],
  ['authentic','adj','B2+','cult','real, not copied','แท้ ของแท้ ดั้งเดิม','Tourists want an authentic local experience.'],
  ['etiquette','n','C1','cult','rules of polite behaviour','มารยาท','Business etiquette differs between East and West.'],
  ['assimilate','v','C1','cult','to become part of a new culture','กลมกลืน','Immigrants assimilate at different speeds.'],
  ['superstition','n','B2+','cult','a belief in luck or magic without evidence','ความเชื่อทางไสยศาสตร์ ความเชื่อโชคลาง','Exam superstitions are tied to anxiety.'],

  /* ---------------------------------------------------------------- CONSUMER TEXTS: ADS & REVIEWS */
  ['complimentary','adj','C1','cons','free, given as a courtesy','ที่ให้ฟรี (เป็นการแสดงน้ำใจ)','The waiter brought a complimentary drink.'],
  ['amenities','n','C1','cons','useful facilities, e.g. a gym or free Wi-Fi','สิ่งอำนวยความสะดวก','The hotel amenities include a rooftop pool.'],
  ['warranty','n','B2+','cons','a written promise to repair a faulty product','การรับประกันสินค้า','The bike comes with a 6-month warranty.'],
  ['refund','n/v','B2','cons','money returned to a buyer','การคืนเงิน','Refunds were provided for the missing drinks.'],
  ['eligible','adj','C1','cons','allowed to receive something','มีสิทธิ์ มีคุณสมบัติ','You are eligible for a discount with a valid ID.'],
  ['valid','adj','B2','cons','legally or officially acceptable','ใช้ได้ (ยังไม่หมดอายุ)','Show a valid student card.'],
  ['subscription','n','B2','cons','money paid regularly for a service','การสมัครสมาชิกแบบรายเดือน/รายปี','A monthly subscription unlocks all lessons.'],
  ['redeem','v','C1','cons','to exchange a coupon for goods','แลก (คูปอง แต้ม)','Redeem the voucher before 31 March.'],
  ['terms and conditions','n','B2+','cons','the rules of an offer or contract','ข้อกำหนดและเงื่อนไข','Terms and conditions apply.'],
  ['durable','adj','B2+','cons','lasting a long time','ทนทาน','The case is durable and waterproof.'],
  ['versatile','adj','C1','cons','useful for many purposes','ใช้งานได้หลากหลาย','The tablet is versatile enough to replace a laptop.'],
  ['drawback','n','C1','cons','a disadvantage','ข้อเสีย','The main drawback is the price.'],
  ['predecessor','n','C1','cons','the earlier model or person before','รุ่นก่อนหน้า ผู้ดำรงตำแหน่งคนก่อน','The X9, like its predecessor, is fast.'],
  ['unmatched','adj','C1','cons','better than all others','ไม่มีใครเทียบได้','As a large tablet, it is unmatched.'],
  ['seamless','adj','C1','cons','smooth, without problems','ราบรื่นไร้รอยต่อ','Checkout is quick and seamless.'],
  ['glitch','n','C1','cons','a small technical problem','ข้อบกพร่องเล็กน้อยทางเทคนิค','A glitch charged me twice.'],
  ['state-of-the-art','adj','C1','cons','the most modern available','ทันสมัยที่สุด','The gym has state-of-the-art machines.'],
  ['courteous','adj','C1','cons','polite and respectful','สุภาพ มีมารยาท','The staff were courteous and efficient.'],
  ['on a budget','phr','B2','cons','with little money to spend','งบประมาณจำกัด','Great for students on a budget.'],
  ['limited time offer','n','B2','cons','a deal that ends soon (urgency technique)','ข้อเสนอพิเศษระยะเวลาจำกัด','Limited time offer: 30% off this week only.'],

  /* ---------------------------------------------------------------- GENERAL ACADEMIC (verbs, adjectives, nouns) */
  ['enhance','v','B2+','acad','to improve','ส่งเสริม ทำให้ดีขึ้น','Awareness can enhance intercultural interaction.'],
  ['undermine','v','C1','acad','to weaken gradually','บ่อนทำลาย ทำให้อ่อนแอลง','Cheating undermines the integrity of education.'],
  ['foster','v','C1','acad','to encourage something to develop','ส่งเสริม บ่มเพาะ','Classrooms should foster curiosity.'],
  ['impede','v','C1','acad','to slow down or block progress','ขัดขวาง','Stress can impede learning.'],
  ['exacerbate','v','C1+','acad','to make a problem worse','ทำให้แย่ลง','Corruption exacerbated the crisis.'],
  ['alleviate','v','C1','acad','to make pain or a problem less severe','บรรเทา','Green spaces alleviate stress.'],
  ['attribute (to)','v','C1','acad','to say something is caused by','ระบุว่าเป็นผลมาจาก','Scientists attribute the decline to environment, not genes.'],
  ['derive (from)','v','C1','acad','to get from a source','ได้มาจาก','Many English words derive from Latin.'],
  ['constitute','v','C1','acad','to form or make up','ประกอบเป็น','Women constitute 29% of the sample.'],
  ['diminish','v','C1','acad','to become or make smaller','ลดลง','Overtourism diminishes quality of life.'],
  ['reinforce','v','C1','acad','to make stronger','เสริมกำลัง ตอกย้ำ','Advertising reinforces fashion norms.'],
  ['perceive','v','C1','acad','to see or understand in a certain way','รับรู้ มองว่า','Westerners may perceive silence as weakness.'],
  ['convey','v','C1','acad','to communicate a message','สื่อ ถ่ายทอด','Posture conveys confidence.'],
  ['pinpoint','v','C1','acad','to identify exactly','ระบุอย่างแม่นยำ','Statistics pinpointed three types of interaction.'],
  ['encroach (on)','v','C1+','acad','to gradually take over something','รุกล้ำ','Gaming began to encroach on her sleep.'],
  ['prioritise','v','B2+','acad','to decide what is most important first','จัดลำดับความสำคัญ','Prioritise tasks with the nearest deadline.'],
  ['vital','adj','B2','acad','extremely important','สำคัญยิ่ง','Creativity is a vital component of learning.'],
  ['ubiquitous','adj','C1','acad','found everywhere','มีอยู่ทั่วไปทุกหนแห่ง','Memes have become ubiquitous.'],
  ['pervasive','adj','C1','acad','spreading widely through something','แพร่หลายไปทั่ว','Technology is pervasive in modern life.'],
  ['nefarious','adj','C1+','acad','wicked, criminal','ชั่วร้าย','Some people use AI for nefarious purposes.'],
  ['commendable','adj','C1','acad','deserving praise','น่ายกย่อง','Your desire to keep everyone happy is commendable.'],
  ['unprecedented','adj','C1','acad','never having happened before','ไม่เคยมีมาก่อน','The flood was unprecedented in scale.'],
  ['inconclusive','adj','C1','acad','not leading to a firm result','ยังไม่ได้ข้อสรุป','The findings were inconclusive.'],
  ['consequential','adj','C1+','acad','important, having big effects','มีความสำคัญ ส่งผลมาก','Beethoven was the most consequential composer of his era.'],
  ['subtle','adj','C1','acad','not obvious','แนบเนียน ละเอียดอ่อน','Researchers will study subtle behaviours like ear twitches.'],
  ['explicit','adj','C1','acad','stated clearly','ชัดเจน ตรงไปตรงมา','The rule is not explicit in the contract.'],
  ['integral','adj','C1','acad','necessary as a part of a whole','เป็นส่วนสำคัญที่ขาดไม่ได้','Memes are an integral part of internet culture.'],
  ['adverse','adj','C1','acad','harmful, negative','ที่เป็นผลเสีย','What is the adverse effect of the ban?'],
  ['prolonged','adj','C1','acad','lasting a long time','ยืดเยื้อ ยาวนาน','Prolonged gaming contributes to inactivity.'],
  ['upshot','n','C1+','acad','the final result','ผลลัพธ์สุดท้าย','The upshot is that any video might be fake.'],
  ['repercussion','n','C1','acad','an unexpected, usually bad, result','ผลกระทบ (มักเป็นทางลบ)','The ban had repercussions for small businesses.'],
  ['scrutiny','n','C1','acad','careful examination','การตรวจสอบอย่างละเอียด','Black shoppers faced unfair scrutiny.'],
  ['integrity','n','C1','acad','honesty; being whole and unbroken','ความซื่อสัตย์ ความสมบูรณ์','Academic integrity matters.'],
  ['phenomenon','n','C1','acad','an observable event or fact','ปรากฏการณ์','White coat syndrome is a common phenomenon.'],
  ['proponent','n','C1','acad','a supporter of an idea','ผู้สนับสนุน','Proponents say vaping helps smokers quit.'],
  ['critic','n','B2','acad','a person who points out faults','ผู้วิจารณ์ ผู้คัดค้าน','Critics say the logo misleads shoppers.'],
  ['trade-off','n','C1','acad','a balance between two things you cannot both have','การได้อย่างเสียอย่าง','Speed versus accuracy is a trade-off.'],
  ['aspiration','n','C1','acad','a strong hope or ambition','ความมุ่งหวัง','Choose a faculty that matches your aspirations.'],
  ['deterioration','n','C1','acad','the process of getting worse','การเสื่อมลง','Scientists try to slow the deterioration that comes with age.'],
  ['propensity','n','C1+','acad','a natural tendency','แนวโน้ม','a growing propensity for "fur babies"'],
  ['incentive','n','C1','acad','something that encourages action','แรงจูงใจ สิ่งจูงใจ','Tax cuts are an incentive to buy EVs.'],

  /* ---------------------------------------------------------------- TONE & ATTITUDE (answer options in tone/attitude items) */
  ['sarcastic','adj','B2+','tone','saying the opposite of what you mean to mock','ประชดประชัน','The poem\'s tone is sarcastic.'],
  ['critical','adj','B2','tone','pointing out faults','เชิงวิพากษ์ ติเตียน','The review is critical of the service.'],
  ['optimistic','adj','B2','tone','hopeful about the future','มองโลกในแง่ดี','The editorial ends on an optimistic note.'],
  ['pessimistic','adj','B2','tone','expecting bad things','มองโลกในแง่ร้าย','The writer is pessimistic about migration.'],
  ['sympathetic','adj','B2','tone','showing understanding of others\' feelings','เห็นอกเห็นใจ','The tone towards the victims is sympathetic.'],
  ['indifferent','adj','B2+','tone','not interested, not caring','เฉยเมย ไม่สนใจ','The officials seemed indifferent.'],
  ['ambivalent','adj','C1','tone','having mixed feelings','รู้สึกสองจิตสองใจ','She is ambivalent about the new rules.'],
  ['skeptical','adj','C1','tone','doubtful','สงสัย ไม่ค่อยเชื่อ','Experts are skeptical of the claims.'],
  ['cautionary','adj','C1','tone','giving a warning','เชิงเตือนสติ','The last paragraph is cautionary.'],
  ['objective','adj','B2+','tone','based on facts, not feelings','เป็นกลาง ตามข้อเท็จจริง','A news report should be objective.'],
  ['balanced','adj','B2','tone','giving both sides fairly','สมดุล มองทั้งสองด้าน','The article gives a balanced view of gaming.'],
  ['informative','adj','B2','tone','giving useful facts','ให้ข้อมูล','The tone of the article is informative.'],
  ['persuasive','adj','B2','tone','trying to make you agree or buy','เชิงโน้มน้าว','The ad uses persuasive language.'],
  ['nostalgic','adj','B2+','tone','fondly remembering the past','โหยหาอดีต','The essay has a nostalgic tone.'],
  ['humorous','adj','B2','tone','funny','ขบขัน','The story is humorous.'],
  ['dismissive','adj','C1','tone','treating something as not worth attention','ไม่ใส่ใจ ปัดตก','His dismissive reply upset the students.'],
  ['admiring','adj','B2+','tone','showing respect and approval','ชื่นชม','The reviewer is admiring of the lead actor.'],
  ['concerned','adj','B2','tone','worried','เป็นห่วง กังวล','The writer is concerned about teen sleep.'],
  ['fearful','adj','B2+','tone','afraid','หวาดกลัว','A fearful tone suggests danger ahead.'],
  ['neutral','adj','B2','tone','not taking a side','เป็นกลาง','The report stays neutral.'],
  ['sentimental','adj','B2+','tone','showing tender, emotional feelings','ที่เน้นอารมณ์ความรู้สึกอ่อนไหว','a sentimental poem about childhood'],
  ['condescending','adj','C1','tone','acting as if others are less intelligent','ดูถูก วางตัวเหนือกว่า','The professor sounded condescending.'],

  /* ---------------------------------------------------------------- GRAPHS & NUMBERS */
  ['fluctuate','v','C1','trend','to rise and fall irregularly','ขึ้นลงไม่แน่นอน','Instagram use fluctuated between 2018 and 2021.'],
  ['peak','n/v','B2','trend','(to reach) the highest point','จุดสูงสุด / ขึ้นถึงจุดสูงสุด','Facebook usage peaked in 2020.'],
  ['level off','v phr','B2+','trend','to stop rising or falling and stay flat','คงที่ (หลังจากขึ้นหรือลง)','Recoveries levelled off in April.'],
  ['plummet','v','C1','trend','to fall very fast','ดิ่งลงอย่างรวดเร็ว','Visitor numbers plummeted during the flood.'],
  ['surge','n/v','C1','trend','(to make) a sudden large rise','พุ่งขึ้นอย่างรวดเร็ว','Sales surged after the video went viral.'],
  ['steady','adj','B2','trend','changing gradually and evenly','คงที่ สม่ำเสมอ','a steady increase'],
  ['marginal','adj','C1','trend','very small','เล็กน้อย','a marginal decrease of 0.5%'],
  ['proportion','n','B2+','trend','a part of a whole','สัดส่วน','The proportion of teens with smartphones is 95%.'],
  ['respondent','n','C1','trend','a person who answers a survey','ผู้ตอบแบบสอบถาม','29% of respondents were women.'],
  ['approximately','adv','B2','trend','about, roughly','ประมาณ','Bangkok had approximately six times as many visitors.'],
  ['cumulative','adj','C1','trend','increasing by adding over time','สะสม','cumulative infections'],
  ['ratio','n','B2+','trend','the relationship between two amounts','อัตราส่วน','a higher plant-to-animal protein ratio'],
  ['outnumber','v','C1','trend','to be more in number than','มีจำนวนมากกว่า','Pets now outnumber children in Taiwan.'],
  ['respectively','adv','C1','trend','in the same order as mentioned','ตามลำดับ','Market shares of 60% and 30% respectively'],

  /* ---------------------------------------------------------------- TEXT ORGANISATION WORDS */
  ['chronological','adj','C1','org','in time order','ตามลำดับเวลา','The news is organised in chronological order.'],
  ['cause and effect','n','B2','org','a pattern showing why something happens and what follows','เหตุและผล','The paragraph follows a cause-and-effect pattern.'],
  ['compare and contrast','n','B2','org','showing similarities and differences','เปรียบเทียบความเหมือนและความต่าง','Article 1 compares and contrasts East and West.'],
  ['problem-solution','n','B2','org','stating a problem, then a way to fix it','ปัญหาและแนวทางแก้ไข','The editorial uses a problem-solution pattern.'],
  ['classification','n','B2+','org','dividing things into groups','การจำแนกประเภท','Waste falls into three classifications.'],
  ['exemplify','v','C1','org','to give an example of','ยกตัวอย่าง','The writer mentions depression to exemplify an emotional condition.'],
  ['general to specific','phr','B2','org','from a broad statement to details','จากภาพรวมสู่รายละเอียด','The paragraph moves from general to specific.'],
  ['anecdote','n','C1','org','a short personal story used as an example','เรื่องเล่าสั้นจากประสบการณ์','The article opens with an anecdote.'],

  /* ---------------------------------------------------------------- IDIOMS & SAYINGS (conversation) */
  ['I\'m all ears','idiom','B2','id','I am listening carefully','ฟังอยู่ เล่ามาเลย','Sure, I\'m all ears. What\'s up?'],
  ['when it rains, it pours','idiom','B2+','id','bad things tend to happen together','เคราะห์ซ้ำกรรมซัด','I lost my wallet and missed the bus — when it rains, it pours.'],
  ['play it by ear','idiom','B2+','id','to decide as things happen, without a plan','ค่อยว่ากันตามสถานการณ์','Let\'s play it by ear tomorrow.'],
  ['go with the flow','idiom','B2','id','to accept what happens without resisting','ปล่อยไปตามน้ำ','On holiday I just go with the flow.'],
  ['stick to the point','idiom','B2+','id','to talk only about the main subject','พูดให้ตรงประเด็น','Please stick to the point or be quiet.'],
  ['draw the line','idiom','C1','id','to set a limit on what you will accept','ขีดเส้น ตั้งขอบเขต','I help my friends, but I draw the line at cheating.'],
  ['out of the blue','idiom','B2','id','suddenly and unexpectedly','อยู่ ๆ ก็เกิดขึ้น','He called me out of the blue.'],
  ['with flying colours','idiom','B2','id','very successfully','อย่างยอดเยี่ยม (สอบผ่านฉลุย)','She passed TGAT with flying colours.'],
  ['see eye to eye','idiom','B2+','id','to agree','เห็นตรงกัน','We don\'t see eye to eye on politics.'],
  ['on cloud nine','idiom','B2','id','extremely happy','มีความสุขมาก','She was on cloud nine after the results.'],
  ['break the ice','idiom','B2','id','to make people relax at the start','ละลายพฤติกรรม','A quick game helped break the ice.'],
  ['a blessing in disguise','idiom','C1','id','something bad that turns out good','เรื่องร้ายที่กลายเป็นดี','Missing the bus was a blessing in disguise.'],
  ['every cloud has a silver lining','idiom','B2+','id','there is something good in every bad situation','ในเรื่องร้ายย่อมมีเรื่องดี','Don\'t worry — every cloud has a silver lining.'],
  ['the last straw','idiom','C1','id','the final problem that makes you lose patience','ฟางเส้นสุดท้าย','The cold coffee was the last straw.'],
  ['hit the books','idiom','B2','id','to study hard','ตั้งใจอ่านหนังสือ','I have to hit the books tonight.'],
  ['cut corners','idiom','C1','id','to do something badly to save time or money','ทำแบบลวก ๆ เพื่อประหยัด','If builders cut corners, a building may not be safe.'],
  ['get cold feet','idiom','C1','id','to become nervous and not want to do something','ใจฝ่อ ไม่กล้าทำในนาทีสุดท้าย','He got cold feet before the speech.'],
  ['count me in','idiom','B2','id','include me','นับฉันด้วย','A movie tonight? Count me in!'],
  ['you can say that again','idiom','B2','id','I completely agree','เห็นด้วยอย่างยิ่ง','"This exam is hard." "You can say that again!"'],
  ['keep your fingers crossed','idiom','B2','id','hope for good luck','ภาวนาให้โชคดี','Keep your fingers crossed for my results.'],
  ['no pain, no gain','idiom','B2','id','you must suffer or work hard to succeed','ไม่มีความสำเร็จใดได้มาง่าย ๆ','No pain, no gain — back to the gym!'],
  ['easier said than done','idiom','B2','id','sounds easy but is hard to do','พูดง่ายแต่ทำยาก','Stop worrying? Easier said than done.'],

  /* ---------------------------------------------------------------- DISCOURSE MARKERS (speech & writing) */
  ['as a matter of fact','dm','B2+','dm','in fact; actually (adds a surprising or stronger point)','อันที่จริงแล้ว','As a matter of fact, she lives in Tokyo, like you.'],
  ['needless to say','dm','C1','dm','obviously, as expected','ไม่ต้องบอกก็รู้ว่า','Needless to say, I was furious.'],
  ['to make matters worse','dm','B2+','dm','adding another bad thing','ยิ่งไปกว่านั้น (เรื่องแย่ลงอีก)','To make matters worse, it started to rain.'],
  ['without further ado','dm','C1','dm','let us begin now','ไม่พูดพร่ำทำเพลง เริ่มกันเลย','Without further ado, let\'s begin.'],
  ['now that','conj','B2+','dm','because now (something is true)','ในเมื่อตอนนี้','Now that you understand Beethoven, any questions?'],
  ['at the end of the day','dm','B2+','dm','when everything is considered','ท้ายที่สุดแล้ว','At the end of the day, learning is about questioning.'],
  ['in other words','dm','B2','dm','to say it differently','พูดอีกอย่างก็คือ','In other words, AI copies music.'],
  ['all things considered','dm','C1','dm','after thinking about everything','เมื่อพิจารณาทุกอย่างแล้ว','All things considered, the trip was a success.'],
  ['having said that','dm','C1','dm','despite what I just said','ถึงอย่างนั้นก็ตาม','It\'s expensive. Having said that, it\'s worth it.'],
  ['by the way','dm','B1','dm','introducing a new topic','อ้อ จะว่าไป','By the way, which music do you prefer?'],
  ['as you can imagine','dm','B2','dm','as you would expect','อย่างที่คุณคงนึกออก','As you can imagine, I\'ve been crying all night.'],
  ['on the other hand','dm','B2','dm','introducing a contrasting point','ในทางกลับกัน','Online classes are flexible. On the other hand, they can be lonely.'],
  ['in that case','dm','B2','dm','if that is true','ถ้าอย่างนั้น','In that case, we\'ll try another restaurant.'],
  ['to be honest','dm','B1','dm','telling the truth frankly','พูดตามตรง','To be honest, we don\'t have much in common.'],
  ['as far as I know','dm','B2','dm','based on what I know','เท่าที่ฉันรู้','As far as I know, some companies don\'t ask for a CV.'],
  ['to put it another way','dm','C1','dm','to explain in different words','พูดอีกนัยหนึ่ง','To put it another way, practice beats talent.'],
  ['more often than not','dm','C1','dm','usually','บ่อยครั้ง ส่วนใหญ่','More often than not, the key is in the next line.'],
  ['in a nutshell','dm','B2+','dm','in summary','โดยสรุปสั้น ๆ','In a nutshell, sleep more and scroll less.'],
  ['mind you','dm','C1','dm','adding a small contrast or warning','แต่ก็นะ (เสริมข้อสังเกต)','It\'s a great phone. Mind you, the battery is weak.'],
  ['even so','dm','C1','dm','despite that','ถึงกระนั้น','The review was harsh. Even so, sales rose.']
];

/* A convenience for the app: vocabulary by theme. */
var LEXICON_THEMES = {
  ai: 'AI & digital life', soc: 'Social media & media literacy', clim: 'Climate & energy',
  dis: 'Disasters & early warning', eco: 'Waste, pollution & consumption', health: 'Health & wellbeing',
  work: 'Education, skills & jobs', cult: 'Culture, communication & society', cons: 'Ads & reviews',
  acad: 'Academic words', tone: 'Tone & attitude', trend: 'Graphs & numbers',
  org: 'Text organisation', id: 'Idioms & sayings', dm: 'Discourse markers'
};
